### ISSUE TITLE
No display_name for some nodes, breaks edges-on-demand

### ISSUE THREAD

**Issue by kawilliams** [alex-r-bigelow/traveler-integrated#19]
I'll look around to find the root of the problem, but this is manifesting itself as an issue when we search for matching nodes for the yellow edges-on-demand. This relates to the corner case I had with the variable "step" -- turns out when you hover over "/phylanx/variable$3$step/2$13$20" (a node of "step" near the top of the tree), it doesn't have performance data related to it (hovering over the node, it has some attributes but doesn't have display_name, count, etc.). @alex-r-bigelow, I think you've mentioned this data-mapping issue before, so I'll see if I can find anything.

**Comment by kawilliams** [comment]
[20190906.zip](https://github.com/alex-r-bigelow/traveler-integrated/files/3789786/20190906.zip)
This dataset that Kate ran in September (the one I have closest on hand)

**Comment by kawilliams** [comment]
Ah, yep, possible values for eval_direct are -1 (undecided), 0 (asynchronous), or 1 (directly)

(Don't worry, I had to write those options onto a sticky note like 18 months ago and frequently refer to it)

**Comment by alex-r-bigelow** [comment]
You're absolutely correct; that's an error! I think it happened because I keyed the primitives shelf/dictionary by primitive name, so there's a collision when the name is an empty string. I'll take another dive in a few minutes (sorry for the delay!)
