### ISSUE TITLE
Jacobi Trace from Kevin not showing all GUID Dependencies

### ISSUE THREAD

**Issue by kisaacs** [alex-r-bigelow/traveler-integrated#24]
These show in traveler-gantt but not traveler-integrated.

**Comment by kisaacs** [comment]
<img width="1365" alt="Screen Shot 2019-11-08 at 9 49 54 AM" src="https://user-images.githubusercontent.com/10036820/68489769-590bd700-020d-11ea-8561-c31756ee96db.png">
<img width="991" alt="Screen Shot 2019-11-08 at 9 51 06 AM" src="https://user-images.githubusercontent.com/10036820/68489773-5c06c780-020d-11ea-8ba6-b7f1acd6778f.png">
There appears to be something off in the lastInterval calculation.

**Comment by alex-r-bigelow** [comment]
All this debugging, and if I had just zoomed in... It looks like each of the intervals that are supposed to be connected just ***slightly*** overlaps its childs' ENTER timestamp, so my bundle script doesn't connect them.

![image](https://user-images.githubusercontent.com/1215873/70339788-a8ddbe00-180c-11ea-942b-3f2ec2a00bcb.png)

![image](https://user-images.githubusercontent.com/1215873/70339812-bc892480-180c-11ea-92f5-eaf29938df98.png)

I'm patching it now to allow connections as long as either the ENTER or LEAVE comes at or before the child's ENTER... but just double-checking that this is really the correct thing to do? This would potentially connect parents that terminate after their children—meaning the line would end up pointing *downstream*. Would this be okay?

**Comment by alex-r-bigelow** [comment]
The result looks something like this:

![image](https://user-images.githubusercontent.com/1215873/70341839-0ffd7180-1811-11ea-9742-d989f284a53d.png)

![image](https://user-images.githubusercontent.com/1215873/70341866-1ab80680-1811-11ea-9a97-962de6e1df35.png)

**Comment by kisaacs** [comment]
It's fine because we don't know where during the interval the child was actually created. This does mess with our heuristic for multi-interval tasks, but that has always been best effort unless we decide to change the data.

Thanks for the fix!
